# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
    minecraft_version=26.1
    loader_version=0.18.4

# Mod Properties
    mod_version=2.13.0+mc.26.1
    maven_group=io.github.apace100
    archives_base_name=Apoli

# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
    fabric_version=0.145.3+26.1.1
    cca_version=8.0.0-alpha.5+26.1
    pal_version=1.13.0
    calio_version=1.15.0+mc.26.1
    clothconfig_version=26.1.154
    modmenu_version=18.0.0-alpha.8
